# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 20:50
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField(blank=True)),
                ('value_low', models.FloatField()),
                ('value_mid', models.FloatField(blank=True, null=True)),
                ('value_high', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'managed': True,
                'ordering': ['date'],
                'verbose_name_plural': 'Data',
                'db_table': 'data',
                'verbose_name': 'Data',
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('model_name', models.TextField(blank=True)),
                ('disease', models.TextField(default='ZVD')),
                ('date_output_generated', models.DateField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
                ('data_file', models.FileField(upload_to='simulation_files')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
                'ordering': ['date_output_generated'],
                'verbose_name_plural': 'Simulation',
                'db_table': 'simulation',
                'verbose_name': 'Simulation',
                'get_latest_by': 'creation_timestamp',
            },
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'get_latest_by': 'creation_timestamp', 'managed': True, 'ordering': ['department', 'municipality'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.RemoveField(
            model_name='location',
            name='data_field_code',
        ),
        migrations.RemoveField(
            model_name='location',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location',
        ),
        migrations.RemoveField(
            model_name='location',
            name='report_date',
        ),
        migrations.RemoveField(
            model_name='location',
            name='value',
        ),
        migrations.AddField(
            model_name='location',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='location',
            name='department_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='municipality_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='department',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='municipality',
            field=models.TextField(blank=True),
        ),
        migrations.AlterModelTable(
            name='location',
            table='location',
        ),
        migrations.AddField(
            model_name='data',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Location'),
        ),
        migrations.AddField(
            model_name='data',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='home.Simulation'),
        ),
    ]
