# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='data_field_code',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='location',
            name='data_type',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='location',
            name='report_date',
            field=models.DateField(default=b'1999-01-01'),
        ),
        migrations.AddField(
            model_name='location',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='department',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='location',
            name='municipality',
            field=models.TextField(default=b''),
        ),
    ]
