# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20161121_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='historical',
            field=models.BooleanField(default=False),
        ),
    ]
