# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-29 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160808_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='examplefile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.TextField(default=b'')),
                ('population', models.TextField(default=b'')),
                ('disease', models.TextField(default=b'')),
                ('name', models.TextField(default=b'')),
                ('output_generate_date', models.DateField()),
                ('value_mid', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('department', models.TextField(default=b'')),
                ('department_code', models.TextField(default=b'')),
                ('municipality', models.TextField(default=b'')),
                ('municipality_code', models.TextField(default=b'')),
            ],
        ),
    ]
