# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20161207_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='sim_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulation_model', to='home.SimulationModel'),
        ),
    ]
