# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160829_0050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='examplefile',
        ),
    ]
