# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20161207_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
