# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_totals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
