# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170117_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
