# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 03:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0010_auto_20170323_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None)),
                ('status', models.TextField(default='New')),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('data_file', models.FileField(blank=True, null=True, upload_to='simulation_files')),
                ('historical', models.BooleanField(default=False)),
                ('progress', models.IntegerField(blank=True, default=0)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
                ('pid', models.TextField(blank=True)),
                ('stdout_file', models.FileField(blank=True, null=True, upload_to='output')),
                ('stderr_file', models.FileField(blank=True, null=True, upload_to='output')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('simulations', models.ManyToManyField(related_name='upload_jobs', to='home.Simulation')),
            ],
        ),
    ]
