# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_uploadjob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadjob',
            options={'managed': True, 'verbose_name': 'Upload Job', 'verbose_name_plural': 'Upload Jobs'},
        ),
        migrations.AlterModelTable(
            name='uploadjob',
            table='upload_job',
        ),
    ]
