# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_uploadjob_upload_start_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='department_code',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='municipality_code',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
