# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20170325_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totals',
            name='data_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='totals',
            name='date_output_generated',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
