# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20170325_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadjob',
            name='upload_end_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
