# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField(blank=True)),
                ('value_low', models.FloatField()),
                ('value_mid', models.FloatField(blank=True, null=True)),
                ('value_high', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'get_latest_by': 'date',
                'managed': True,
                'ordering': ['date'],
                'verbose_name_plural': 'Data',
                'db_table': 'data',
                'verbose_name': 'Data',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.TextField(blank=True)),
                ('department_code', models.TextField(blank=True)),
                ('municipality', models.TextField(blank=True)),
                ('municipality_code', models.TextField(blank=True)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'get_latest_by': 'creation_timestamp',
                'managed': True,
                'ordering': ['department', 'municipality'],
                'verbose_name_plural': 'Locations',
                'db_table': 'location',
                'verbose_name': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('model_name', models.TextField(blank=True)),
                ('disease', models.TextField(default=b'ZVD')),
                ('date_output_generated', models.DateField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now=True)),
                ('data_file', models.FileField(upload_to=b'simulation_files')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'creation_timestamp',
                'managed': True,
                'ordering': ['date_output_generated'],
                'verbose_name_plural': 'Simulation',
                'db_table': 'simulation',
                'verbose_name': 'Simulation',
            },
        ),
        migrations.AddField(
            model_name='data',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.Location'),
        ),
        migrations.AddField(
            model_name='data',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='simulation.Simulation'),
        ),
    ]
