# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_browser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='zikacasescolumbia',
            table='zika_cases',
        ),
    ]
